# Comprehensive Test Configuration for Context Memory Store
# Used for running infrastructure validation and connectivity tests
# 
# ⚠️ PROOF OF CONCEPT ONLY - NOT FOR PRODUCTION USE
# 
# SECURITY NOTE: This test configuration inherits the same intentional
# security decisions as the main system (disabled auth, unrestricted access).
# See SECURITY.md for complete documentation of these deliberate choices.

services:
  # Main test orchestrator
  test-runner:
    image: curlimages/curl:latest
    container_name: context-memory-test-runner
    depends_on:
      qdrant:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    networks:
      - context-memory-network
    command: |
      sh -c '
        echo "🧪 Starting comprehensive infrastructure tests..."
        echo "================================================"
        echo ""
        
        # Function to test endpoint with retries
        test_endpoint() {
          local url=$$1
          local name=$$2
          local retries=3
          local delay=5
          
          for i in $$(seq 1 $$retries); do
            if curl -s --max-time 10 -f "$$url" > /dev/null; then
              echo "✅ $$name is accessible"
              return 0
            fi
            if [ $$i -lt $$retries ]; then
              echo "⚠️  $$name not ready, retrying in $${delay}s... ($$i/$$retries)"
              sleep $$delay
            fi
          done
          echo "❌ $$name failed after $$retries attempts"
          return 1
        }
        
        # Test service health endpoints
        echo "🔍 Testing service health endpoints..."
        test_endpoint "http://qdrant:6333/health" "Qdrant health" || exit 1
        test_endpoint "http://neo4j:7474/" "Neo4j web interface" || exit 1
        test_endpoint "http://prometheus:9090/-/healthy" "Prometheus health" || exit 1
        test_endpoint "http://grafana:3000/api/health" "Grafana health" || exit 1
        echo ""
        
        # Test metrics endpoints
        echo "📊 Testing metrics endpoints..."
        test_endpoint "http://qdrant:6333/metrics" "Qdrant metrics" || exit 1
        test_endpoint "http://neo4j:2004/metrics" "Neo4j metrics" || exit 1
        test_endpoint "http://prometheus:9090/metrics" "Prometheus metrics" || exit 1
        test_endpoint "http://grafana:3000/metrics" "Grafana metrics" || exit 1
        echo ""
        
        # Test Ollama external connectivity
        echo "🤖 Testing external Ollama connectivity..."
        if curl -s --max-time 10 -f "http://host.docker.internal:11434/api/version" > /dev/null; then
          echo "✅ Ollama external service is accessible"
          
          # Test Ollama API endpoints
          if curl -s --max-time 10 -f "http://host.docker.internal:11434/api/tags" > /dev/null; then
            echo "✅ Ollama API endpoints responding"
          else
            echo "⚠️  Ollama API endpoints not fully responsive"
          fi
        else
          echo "⚠️  Ollama external service not accessible (this is optional for infrastructure testing)"
        fi
        echo ""
        
        # Test Qdrant functionality
        echo "🔍 Testing Qdrant basic functionality..."
        # Create a test collection
        curl -s -X PUT "http://qdrant:6333/collections/test-collection" \
          -H "Content-Type: application/json" \
          -d "{\"vectors\": {\"size\": 4, \"distance\": \"Cosine\"}}" > /dev/null
        
        if [ $$? -eq 0 ]; then
          echo "✅ Qdrant collection creation successful"
          
          # List collections to verify
          if curl -s "http://qdrant:6333/collections" | grep -q "test-collection"; then
            echo "✅ Qdrant collection listing working"
          else
            echo "⚠️  Qdrant collection not found in listing"
          fi
        else
          echo "❌ Qdrant collection creation failed"
          exit 1
        fi
        echo ""
        
        # Test Neo4j functionality  
        echo "🔗 Testing Neo4j basic functionality..."
        # Neo4j authentication disabled for local development
        
        # Test Neo4j basic query (no auth)
        if curl -s --max-time 10 \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"RETURN 1 as test\"}]}" | grep -q "test"; then
          echo "✅ Neo4j basic queries working"
        else
          echo "❌ Neo4j query execution failed"
          exit 1
        fi
        echo ""
        
        # Test Prometheus targets
        echo "📈 Testing Prometheus configuration..."
        if curl -s "http://prometheus:9090/api/v1/targets" | grep -q "neo4j\|qdrant\|grafana"; then
          echo "✅ Prometheus has configured targets"
        else
          echo "⚠️  Prometheus targets may not be fully configured"
        fi
        echo ""
        
        # Test Grafana data source connectivity
        echo "📊 Testing Grafana functionality..."
        GRAFANA_USER="admin"
        GRAFANA_PASS="contextmemory"
        
        if curl -s --max-time 10 -u "$$GRAFANA_USER:$$GRAFANA_PASS" \
          "http://grafana:3000/api/datasources" | grep -q "prometheus"; then
          echo "✅ Grafana can access data sources"
        else
          echo "⚠️  Grafana data source configuration may need attention"
        fi
        echo ""
        
        echo "🎉 All infrastructure tests completed successfully!"
        echo "================================================"
        exit 0
      '
    
  # Neo4j APOC and connectivity validator
  neo4j-validator:
    image: curlimages/curl:latest
    container_name: context-memory-neo4j-validator
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - context-memory-network
    profiles:
      - extended-tests
    command: |
      sh -c '
        echo "🔗 Running extended Neo4j APOC validation..."
        
        # Test APOC availability (no auth - disabled for local development)
        echo "Testing APOC procedures availability..."
        if curl -s \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"CALL apoc.help(\\\"apoc\\\") YIELD name RETURN count(name) as apoc_procedures\"}]}" | grep -q "apoc_procedures"; then
          echo "✅ APOC procedures are available"
        else
          echo "❌ APOC procedures not available"
          exit 1
        fi
        
        # Test specific APOC functionality
        echo "Testing APOC utility functions..."
        if curl -s \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"RETURN apoc.version() as version\"}]}" | grep -q "version"; then
          echo "✅ APOC utility functions working"
        else
          echo "❌ APOC utility functions not working"
          exit 1
        fi
        
        # Test APOC graph operations
        echo "Testing APOC graph operations..."
        test_label="APOCTest$(date +%s)"
        
        # Create test data using APOC
        if curl -s \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"CALL apoc.create.node([\\\"$$test_label\\\"], {name: \\\"test\\\", created: timestamp()}) YIELD node RETURN node.name as name\"}]}" | grep -q "test"; then
          echo "✅ APOC node creation working"
        else
          echo "❌ APOC node creation failed"
          exit 1
        fi
        
        # Test APOC path operations
        if curl -s \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"MATCH (n:$$test_label) CALL apoc.path.expand(n, null, null, 1, 1) YIELD path RETURN count(path) as path_count\"}]}" | grep -q "path_count"; then
          echo "✅ APOC path operations working"
        else
          echo "⚠️  APOC path operations may not be working (this is expected for single nodes)"
        fi
        
        # Cleanup test data
        curl -s \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"MATCH (n:$$test_label) DELETE n\"}]}" > /dev/null
        
        # Test metrics endpoint (if configured)
        echo "Testing Neo4j metrics endpoint..."
        if curl -s --max-time 5 "http://neo4j:2004/metrics" | grep -q "neo4j"; then
          echo "✅ Neo4j metrics endpoint working"
        else
          echo "⚠️  Neo4j metrics endpoint not configured or not working"
        fi
        
        echo "Neo4j extended APOC validation complete"
      '

  # Comprehensive Service Functionality Validator (Addresses Issue #18)
  comprehensive-validator:
    image: alpine:latest
    container_name: context-memory-comprehensive-validator
    depends_on:
      qdrant:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
    networks:
      - context-memory-network
    profiles:
      - comprehensive-tests
    command: |
      sh -c '
        # Install curl
        apk add --no-cache curl
        
        echo "🔍 Comprehensive Service Functionality Testing (Issue #18)"
        echo "=========================================================="
        
        # Test Qdrant comprehensive functionality
        echo "🔍 Testing Qdrant comprehensive vector operations..."
        TEST_COLLECTION="docker-test-$(date +%s)"
        
        # Create collection
        if curl -s --max-time 15 -X PUT "http://qdrant:6333/collections/$$TEST_COLLECTION" \
          -H "Content-Type: application/json" \
          -d "{\"vectors\": {\"size\": 4, \"distance\": \"Cosine\"}}" | grep -q "\"result\":true"; then
          echo "✅ Qdrant collection creation successful"
        else
          echo "❌ Qdrant collection creation failed"
          exit 1
        fi
        
        # Batch vector insertion
        vectors_json="{\"points\":[{\"id\":1,\"vector\":[0.1,0.2,0.3,0.4],\"payload\":{\"text\":\"test doc 1\",\"category\":\"validation\"}},{\"id\":2,\"vector\":[0.5,0.6,0.7,0.8],\"payload\":{\"text\":\"test doc 2\",\"category\":\"validation\"}}]}"
        
        if curl -s --max-time 15 -X PUT "http://qdrant:6333/collections/$$TEST_COLLECTION/points" \
          -H "Content-Type: application/json" \
          -d "$$vectors_json" | grep -q "\"status\":\"acknowledged\""; then
          echo "✅ Qdrant batch vector insertion successful"
        else
          echo "❌ Qdrant batch vector insertion failed"
          exit 1
        fi
        
        # Vector search with payload
        if curl -s --max-time 15 -X POST "http://qdrant:6333/collections/$$TEST_COLLECTION/points/search" \
          -H "Content-Type: application/json" \
          -d "{\"vector\":[0.1,0.2,0.3,0.4],\"limit\":2,\"with_payload\":true}" | grep -q "validation"; then
          echo "✅ Qdrant vector search with payload working"
        else
          echo "❌ Qdrant vector search with payload failed"
          exit 1
        fi
        
        # Filter-based search
        if curl -s --max-time 15 -X POST "http://qdrant:6333/collections/$$TEST_COLLECTION/points/search" \
          -H "Content-Type: application/json" \
          -d "{\"vector\":[0.1,0.2,0.3,0.4],\"limit\":1,\"filter\":{\"must\":[{\"key\":\"category\",\"match\":{\"value\":\"validation\"}}]},\"with_payload\":true}" | grep -q "validation"; then
          echo "✅ Qdrant filter-based search working"
        else
          echo "❌ Qdrant filter-based search failed"
          exit 1
        fi
        
        # Test Prometheus comprehensive functionality
        echo "🔍 Testing Prometheus comprehensive metrics collection..."
        
        # Validate targets
        if curl -s --max-time 15 "http://prometheus:9090/api/v1/targets" | grep -q "\"job\":\"qdrant\""; then
          echo "✅ Prometheus Qdrant target configured"
        else
          echo "⚠️  Prometheus Qdrant target not configured"
        fi
        
        if curl -s --max-time 15 "http://prometheus:9090/api/v1/targets" | grep -q "\"job\":\"grafana\""; then
          echo "✅ Prometheus Grafana target configured"
        else
          echo "⚠️  Prometheus Grafana target not configured"
        fi
        
        # Test query aggregation
        if curl -s --max-time 15 "http://prometheus:9090/api/v1/query?query=count(up)" | grep -q "\"value\""; then
          echo "✅ Prometheus aggregation queries working"
        else
          echo "❌ Prometheus aggregation queries failed"
          exit 1
        fi
        
        # Test Grafana comprehensive functionality
        echo "🔍 Testing Grafana comprehensive dashboard connectivity..."
        
        # Data source connectivity
        if curl -s --max-time 15 "http://grafana:3000/api/datasources" | grep -q "prometheus"; then
          echo "✅ Grafana Prometheus data source configured"
        else
          echo "❌ Grafana Prometheus data source not configured"
          exit 1
        fi
        
        # Query proxy test
        datasource_id=$(curl -s --max-time 15 "http://grafana:3000/api/datasources" | grep -o "\"id\":[0-9]*" | head -1 | grep -o "[0-9]*")
        if [ -n "$$datasource_id" ] && curl -s --max-time 15 "http://grafana:3000/api/datasources/proxy/$$datasource_id/api/v1/query?query=up" | grep -q "\"data\""; then
          echo "✅ Grafana query proxy to Prometheus working"
        else
          echo "⚠️  Grafana query proxy may have issues"
        fi
        
        # Test end-to-end connectivity
        echo "🔍 Testing end-to-end service connectivity..."
        
        # Neo4j + Qdrant concurrent operations
        neo4j_result=$(curl -s --max-time 15 \
          -H "Content-Type: application/json" \
          -X POST "http://neo4j:7474/db/neo4j/tx/commit" \
          -d "{\"statements\":[{\"statement\":\"RETURN timestamp() as neo4j_time\"}]}")
        
        qdrant_result=$(curl -s --max-time 15 "http://qdrant:6333/collections/$$TEST_COLLECTION")
        
        if echo "$$neo4j_result" | grep -q "neo4j_time" && echo "$$qdrant_result" | grep -q "points_count"; then
          echo "✅ Neo4j and Qdrant concurrent operations working"
        else
          echo "❌ Neo4j and Qdrant concurrent operations failed"
          exit 1
        fi
        
        # Test coverage validation (addresses Issue #12)
        echo "🔍 Test Coverage Validation (Issue #12)..."
        
        # Verify data persistence
        if curl -s --max-time 15 "http://qdrant:6333/collections/$$TEST_COLLECTION" | grep -q "\"points_count\":2"; then
          echo "✅ Test data persisted correctly"
        else
          echo "❌ Test data not persisted correctly"
          exit 1
        fi
        
        # Cleanup
        curl -s --max-time 15 -X DELETE "http://qdrant:6333/collections/$$TEST_COLLECTION" > /dev/null
        echo "✅ Test cleanup completed"
        
        echo "=========================================================="
        echo "🎉 All comprehensive service functionality tests passed!"
        echo ""
        echo "Summary:"
        echo "✅ Qdrant: Vector operations, batch insertion, filtered search"
        echo "✅ Prometheus: Target validation, query aggregation"
        echo "✅ Grafana: Data source connectivity, query proxy"
        echo "✅ End-to-end: Service connectivity validated"
        echo "✅ Test Coverage: Functional operations confirmed (Issue #12)"
      '
      
  # Ollama connectivity validator (only runs if Ollama is available)
  ollama-validator:
    image: curlimages/curl:latest
    container_name: context-memory-ollama-validator
    networks:
      - context-memory-network
    profiles:
      - extended-tests
    command: |
      sh -c '
        echo "🤖 Running extended Ollama validation..."
        
        # Test if Ollama is running and responsive
        if curl -s --max-time 15 "http://host.docker.internal:11434/api/version"; then
          echo "✅ Ollama version endpoint accessible"
          
          # Test model listing
          if curl -s --max-time 15 "http://host.docker.internal:11434/api/tags" | grep -q "models"; then
            echo "✅ Ollama model listing working"
          else
            echo "⚠️  No models found in Ollama"
          fi
        else
          echo "⚠️  Ollama service not accessible - skipping extended tests"
        fi
        
        echo "Ollama extended validation complete"
      '

  # Include all services from main docker-compose
  qdrant:
    extends:
      file: docker-compose.yml
      service: qdrant

  neo4j-apoc-downloader:
    extends:
      file: docker-compose.yml
      service: neo4j-apoc-downloader

  neo4j:
    extends:
      file: docker-compose.yml
      service: neo4j

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus

  grafana:
    extends:
      file: docker-compose.yml
      service: grafana

networks:
  context-memory-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  prometheus_data:
  grafana_data: