global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Qdrant metrics
  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: /metrics
    scrape_interval: 30s

  # Neo4j metrics
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: /metrics
    scrape_interval: 30s

  # Ollama metrics (if available)
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Context Memory Store API (placeholder for future phases)
  # - job_name: 'context-api'
  #   static_configs:
  #     - targets: ['context-api:8080']
  #   metrics_path: /metrics
  #   scrape_interval: 15s

  # System metrics (if node_exporter is added)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']

# Alerting configuration (placeholder for future use)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Optional: Remote write configuration for long-term storage
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"