service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_cors: true

storage:
  # Path to the directory where the data is stored
  storage_path: /qdrant/storage
  # Enable Write-Ahead Logging for better durability
  wal_capacity_mb: 32
  # Snapshot threshold for persistence
  snapshot_threshold_mb: 1024
  # Performance tuning
  performance:
    max_search_threads: 0  # Use all available cores
    max_optimization_threads: 1

cluster:
  # Single node configuration for local development
  enabled: false

# Security configuration for production use
# tls:
#   cert: /etc/ssl/certs/qdrant.crt
#   key: /etc/ssl/private/qdrant.key

# API key configuration for production use
# api_key: "your-api-key-here"

# Logging configuration
log_level: "INFO"